resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/Build
      endpoint: templates 

steps:
- template: dotnet.yml@templates

  
# echo PullRequest  49e27cc18f57870206171925a8c540abdac7bbfb 2.0.0
# echo IndividualCI 036100265b6d83d536827451131bf8c306ce9d43 2.0.0