# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


pool: Default
#  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- bash: |
    export VERSION=$(git tag --sort=-version:refname | head -1)
    echo $BUILD_REASON $BUILD_SOURCEVERSION $VERSION
    echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
    echo $(version)
  displayName: Set Version

- checkout: self
  submodules: recursive

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'Specifications/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

# echo PullRequest  49e27cc18f57870206171925a8c540abdac7bbfb 2.0.0
# echo IndividualCI 036100265b6d83d536827451131bf8c306ce9d43 2.0.0