# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: Default
#  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  CASCADE: 6a011156-dec2-44a1-b4f6-718ddc28c413 a5f5239e-c774-4933-ae09-6573de30e5ef

steps:
- bash: |
    export VERSION=$(git tag --sort=-version:refname | head -1)
    echo $BUILD_REASON $BUILD_SOURCEVERSION $VERSION
    echo "##vso[task.setvariable variable=VERSION]$VERSION"

    echo "Cascade to:"
    for item in ${CASCADE[*]}
    do
      printf "  %s\n" $item
    done
  displayName: Set Version

- script: |
    echo The version is $(VERSION)
  displayName: Show version

- checkout: self
  submodules: recursive

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'

- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Build release
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'Specifications/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
  
# echo PullRequest  49e27cc18f57870206171925a8c540abdac7bbfb 2.0.0
# echo IndividualCI 036100265b6d83d536827451131bf8c306ce9d43 2.0.0