# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: Default
#  vmImage: 'ubuntu-16.04'

variables:
  version: 1.0.0
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- bash: echo $(version)
- bash: echo '##vso[task.setvariable variable=version]2.0.0'
- bash: echo $(version)
- bash: echo $(Build.Reason)
- bash: echo '##vso[task.setvariable variable=Build.BuildNumber]2.0.0'

- checkout: self
  submodules: recursive

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'Specifications/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
